# Scaling thresholds

CPU_SCALE_UP = 70
CPU_SCALE_DOWN = 35

MEMORY_SCALE_UP = 75
MEMORY_SCALE_DOWN = 40

QUEUE_SCALE_UP = 100
QUEUE_SCALE_DOWN = 30

MAX_INSTANCES = 10
MIN_INSTANCES = 1

SCALE_UP_COOLDOWN = 120     # seconds
SCALE_DOWN_COOLDOWN = 300
